ALTER TABLE participants ADD COLUMN address TEXT DEFAULT NULL;
ALTER TABLE participants ADD COLUMN city    TEXT DEFAULT NULL;
ALTER TABLE participants ADD COLUMN state   TEXT DEFAULT NULL;
ALTER TABLE participants ADD COLUMN zip     TEXT DEFAULT NULL;
