ALTER TABLE donations ADD COLUMN address TEXT DEFAULT NULL;
ALTER TABLE donations ADD COLUMN city    TEXT DEFAULT NULL;
ALTER TABLE donations ADD COLUMN state   TEXT DEFAULT NULL;
ALTER TABLE donations ADD COLUMN zip     TEXT DEFAULT NULL;
